import { Roboto } from "next/font/google";
import "./globals.css";
import Orb from "./Orb"
import Nav from "./components/nav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* Fixed Fullscreen Background */}
        <Nav />
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            zIndex: -1,
            overflow: "hidden",
          }}
        >
          <Orb
            hoverIntensity={0.9}
            rotateOnHover={true}
            hue={0}
            forceHoverState={false}
          />
        </div>
        
        <div className="page-content">{children}</div>
      </body>
    </html>
  );
}
